-- Corrective backfill for availability_rules.created_at.
--
-- The previous migration (20260512000000_add_availability_rule_created_at) added
-- the column with `NOT NULL DEFAULT CURRENT_TIMESTAMP`, which caused Postgres to
-- backfill every existing row with the migration timestamp. That made every
-- pre-existing rule look like it was "added today" in the admin dashboard.
--
-- Best available proxy for the real creation time is the earliest slot start_time
-- generated by the rule. Coaches typically schedule near-term availability, so
-- this is usually within a few days of when they actually created the rule.
-- Fall back to first_start_time on the rule for rules with no slots.
--
-- We only touch rows whose created_at falls in a narrow window around the first
-- broken migration's run time, so re-running on a fresh DB (where the migration
-- never produced bogus data) is a no-op.

UPDATE "availability_rules" r
SET "created_at" = COALESCE(
  (SELECT MIN(s."start_time") FROM "availability_slots" s WHERE s."rule_id" = r."id"),
  r."first_start_time"
)
WHERE "created_at" BETWEEN '2026-05-12 00:00:00' AND '2026-05-13 00:00:00';
