#!/usr/bin/env bash
# Write .env from the deployed stack so the web build gets API URL and Cognito config.
# Run once after deploy (or when you switch stage). Then 'npm run deploy:web' just works.
#
# Usage: ./scripts/env-from-stack.sh [stage]
# Stage defaults to "dev".

set -e
STAGE="${1:-dev}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

STACK_NAME="apex-sports-${STAGE}"
echo "Reading outputs from stack: $STACK_NAME"

API_URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text 2>/dev/null || true)
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text 2>/dev/null || true)
USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text 2>/dev/null || true)

if [ -z "$API_URL" ] || [ "$API_URL" == "None" ]; then
  echo "Error: Could not get ApiUrl from stack $STACK_NAME. Is the stack deployed?" >&2
  exit 1
fi
if [ -z "$USER_POOL_ID" ] || [ "$USER_POOL_ID" == "None" ]; then
  echo "Error: Could not get UserPoolId from stack $STACK_NAME." >&2
  exit 1
fi
if [ -z "$USER_POOL_CLIENT_ID" ] || [ "$USER_POOL_CLIENT_ID" == "None" ]; then
  echo "Error: Could not get UserPoolClientId from stack $STACK_NAME." >&2
  exit 1
fi

ENV_FILE="$ROOT_DIR/.env"
cat > "$ENV_FILE" << EOF
# Generated by scripts/env-from-stack.sh ($STAGE) — used by deploy:web and local dev
VITE_API_URL=$API_URL
VITE_COGNITO_USER_POOL_ID=$USER_POOL_ID
VITE_COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_COGNITO_REGION=us-east-1
EOF

echo "Wrote $ENV_FILE"
echo "Run: npm run deploy:web"
